### ISSUE TITLE
What is a directionUV?

### ISSUE THREAD

**Issue by ferrolho** [lo-th/fullik#4]
Sorry for the ignorance, but I am not being able to figure out what directionUV stands for...

For example: `addConsecutiveFreelyRotatingHingedBone (directionUV, length, type, hingeRotationAxis)`

**Comment by ghost** [comment]
It's the direction of the bone (from the start location to the end location) as specified as a unit vector - that is, the x/y/z axis values are all between -1.0 and +1.0. So to put it another way, it's the normalised direction of the bone.

For example (1, 0, 0) would be directly to the right in global space because it's 1.0 on the x-axis, and nothing on the y and z axes.

Take a look at the original Caliko source code (https://github.com/feduni/caliko) and its documentation for further details.
